"""
Functional test for predict_index against a REAL RadiantSwap create-tx.

Proves the Python RMKT-beacon + singleton-state parsing/verification matches the SDK byte layout
(fixture generated by the RadiantSwap SDK buildCreateMarket). Run: PYTHONPATH=. python3 tests/test_predict_index.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from electrumx.server.predict_index import (  # noqa: E402
    PredictionMarketIndex, parse_market_beacon, parse_singleton_state,
)

FIX = json.load(open(os.path.join(os.path.dirname(__file__), 'fixtures', 'rmkt_create.json')))


class _Out:
    def __init__(self, script_hex):
        self.pk_script = bytes.fromhex(script_hex)


class _Tx:
    def __init__(self, output_hexes):
        self.outputs = [_Out(h) for h in output_hexes]


class _StubUtxoDB:
    def get(self, key):
        return None


class _StubDB:
    db_height = 500000
    utxo_db = _StubUtxoDB()


class _Env:
    predict_index = True
    reorg_limit = 0


def _idx():
    return PredictionMarketIndex(_StubDB(), _Env())


def _spent_set():
    return {bytes.fromhex(s) for s in FIX['spent']}


def _outputs():
    return [FIX['out0'], FIX['out1'], FIX['out2'], FIX['beacon']]


def test_beacon_and_state_parse():
    b = parse_market_beacon(bytes.fromhex(FIX['beacon']))
    assert b is not None, 'beacon failed to parse'
    assert b['market_ref'].hex() == FIX['marketRef']
    assert b['yes_ref'].hex() == FIX['yesRef']
    assert b['no_ref'].hex() == FIX['noRef']
    assert b['question'] == FIX['question']
    assert b['b_expiry'] == FIX['expiry'] and b['b_grace'] == FIX['grace']
    s = parse_singleton_state(bytes.fromhex(FIX['out0']))
    assert s is not None, 'singleton state failed to parse'
    assert s['status'] == 0 and s['expiry'] == FIX['expiry'] and s['grace'] == FIX['grace']
    assert s['oracle'].hex() == FIX['oracle']
    print('  ok: beacon + singleton state parse, match SDK layout')


def test_honest_market_recorded():
    idx = _idx()
    tx_hash = bytes.fromhex(FIX['marketRef'][:64])  # arbitrary
    idx.process_tx(tx_hash, _Tx(_outputs()), height=500001, tx_idx=0, spent_outpoints=_spent_set())
    rec = idx.get_market(bytes.fromhex(FIX['marketRef']))
    assert rec is not None, 'honest market was not recorded'
    assert rec['question'] == FIX['question']
    assert rec['expiry'] == FIX['expiry'] and rec['grace'] == FIX['grace']  # from chain state
    assert rec['oracle'] == FIX['oracle']
    assert rec['beacon_params_match'] is True
    assert rec['status_at_creation'] == 0
    print('  ok: honest market recorded with chain-sourced params + question')


def test_reject_not_inducible():
    idx = _idx()
    # spent set WITHOUT the marketRef outpoint -> not inducible -> rejected
    spent = {s for s in _spent_set() if s != bytes.fromhex(FIX['marketRef'])}
    idx.process_tx(b'\x00' * 32, _Tx(_outputs()), height=1, tx_idx=0, spent_outpoints=spent)
    assert idx.get_market(bytes.fromhex(FIX['marketRef'])) is None, 'forged (non-inducible) beacon was recorded!'
    print('  ok: beacon rejected when marketRef is not a spent outpoint')


def test_reject_out0_not_singleton():
    idx = _idx()
    # swap out0 with the yes-anchor so output[0] is not the marketRef singleton
    bad = [FIX['out1'], FIX['out0'], FIX['out2'], FIX['beacon']]
    idx.process_tx(b'\x00' * 32, _Tx(bad), height=1, tx_idx=0, spent_outpoints=_spent_set())
    assert idx.get_market(bytes.fromhex(FIX['marketRef'])) is None, 'beacon recorded with wrong out0!'
    print('  ok: beacon rejected when output[0] is not the deployed singleton')


def test_reject_anchor_missing_ref():
    idx = _idx()
    # replace out2 (no-anchor) with out0 so the no_ref is absent from output[2]
    bad = [FIX['out0'], FIX['out1'], FIX['out0'], FIX['beacon']]
    idx.process_tx(b'\x00' * 32, _Tx(bad), height=1, tx_idx=0, spent_outpoints=_spent_set())
    assert idx.get_market(bytes.fromhex(FIX['marketRef'])) is None, 'beacon recorded with wrong anchor!'
    print('  ok: beacon rejected when an anchor does not carry its ref')


def _push(data: bytes) -> bytes:
    n = len(data)
    if n < 0x4c:
        return bytes([n]) + data
    if n <= 0xff:
        return bytes([0x4c, n]) + data
    if n <= 0xffff:
        return bytes([0x4d]) + n.to_bytes(2, 'little') + data
    return bytes([0x4e]) + n.to_bytes(4, 'little') + data


def _rmkt(question: bytes) -> bytes:
    b = bytes.fromhex
    return (bytes([0x6a]) + _push(b'RMKT') + _push(bytes([1]))
            + _push(b(FIX['marketRef'])) + _push(b(FIX['yesRef'])) + _push(b(FIX['noRef']))
            + _push((444444).to_bytes(4, 'little')) + _push((50).to_bytes(4, 'little'))
            + _push(b(FIX['oracle'])) + _push(question))


def test_reject_oversized_question():
    # REDTEAM-FIX (high): an oversized question would later overflow struct.pack('<H', len(q)) in
    # to_bytes() at flush -> chain-halt. parse_market_beacon must reject it BEFORE it is stored.
    from electrumx.server.predict_index import parse_market_beacon, QUESTION_MAX_BYTES, MarketRecord
    ok = parse_market_beacon(_rmkt(b'A' * QUESTION_MAX_BYTES))
    assert ok is not None and ok['question'] == 'A' * QUESTION_MAX_BYTES, 'max-size question should parse'
    huge = parse_market_beacon(_rmkt(b'A' * (QUESTION_MAX_BYTES + 1)))
    assert huge is None, 'oversized question must be rejected at parse (anti chain-halt)'
    over = parse_market_beacon(_rmkt(b'A' * 70000))
    assert over is None, '70 KB question must be rejected'
    # belt: to_bytes truncates so struct.pack('<H') can never raise even if a long question slips in
    rec = MarketRecord(market_ref=bytes(36), yes_ref=bytes(36), no_ref=bytes(36), expiry=1, grace=1,
                       oracle=bytes(33), status=0, optimistic=False, beacon_params_match=True,
                       question='Z' * 100000, create_txid=bytes(32), create_height=1)
    rec.to_bytes()  # must NOT raise
    print('  ok: oversized question rejected at parse; to_bytes truncates (no chain-halt)')


if __name__ == '__main__':
    test_beacon_and_state_parse()
    test_honest_market_recorded()
    test_reject_not_inducible()
    test_reject_out0_not_singleton()
    test_reject_anchor_missing_ref()
    test_reject_oversized_question()
    print('\nALL PREDICT_INDEX TESTS PASS')
