"""Parity test for the royalty-listing parser.

The vectors below are produced by Photonic's `royaltySaleScript` /
`royaltyBeaconScript` (packages/lib/src/royaltyCovenant.ts, pinned in
royaltyVector.test.ts). The covenant carries NO on-chain version/length marker,
so this parser MUST stay byte-for-byte in lockstep with that builder — if the
builder changes, regenerate these vectors and re-verify here. The txid is
deliberately non-palindromic so a byte-order regression cannot hide.
"""
from electrumx.server.royalty_index import (
    parse_royalty_sale_script,
    parse_royalty_beacon,
    _format_ref,
    RRYL_VERSION,
)

# --- vectors generated by royaltyVector.test.ts (price=100000, royalty 5%=5000) ---
REF_HEX = (
    "0011223344556677889900aabbccddeeff"
    "00112233445566778899aabbccddee03000000"
)
PKH_HEX = "62e907b15cbf27d5425399ebf6f0fb50ebb88f18"
P2PKH_HEX = "76a914" + PKH_HEX + "88ac"
COVHEX = (
    "d80011223344556677889900aabbccddeeff00112233445566778899aabbccddee03000000"
    "756376a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac6700cd19"
    "76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac8800cc03a08601a26952cd19"
    "76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac8852cc028813a2695168"
)
BEACONHEX = (
    "6a045252594c5124"
    "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee03000000"
)


def test_parse_covenant_matches_builder():
    p = parse_royalty_sale_script(bytes.fromhex(COVHEX))
    assert p is not None
    assert p["ref"].hex() == REF_HEX
    assert p["pkh"].hex() == PKH_HEX
    assert p["seller_script"].hex() == P2PKH_HEX
    assert p["price"] == 100000
    assert len(p["royalties"]) == 1
    rscript, rvalue = p["royalties"][0]
    assert rscript.hex() == P2PKH_HEX
    assert rvalue == 5000


def test_parse_beacon_matches_builder():
    b = parse_royalty_beacon(bytes.fromhex(BEACONHEX))
    assert b is not None
    # libauth minimal-push encodes version 1 as OP_1 (0x51); parser decodes to 1.
    assert b["version"] == 1 == RRYL_VERSION
    assert b["ref"].hex() == REF_HEX


def test_beacon_ref_matches_covenant_ref():
    cov = parse_royalty_sale_script(bytes.fromhex(COVHEX))
    bea = parse_royalty_beacon(bytes.fromhex(BEACONHEX))
    assert cov is not None and bea is not None
    assert cov["ref"] == bea["ref"]


def test_format_ref_reverses_txid_and_decodes_vout():
    # display form = big-endian txid + "_" + decimal vout (non-palindrome proof).
    ref = bytes.fromhex(REF_HEX)
    expected = ref[:32][::-1].hex() + "_3"
    assert _format_ref(ref) == expected


def test_rejects_malformed():
    assert parse_royalty_sale_script(b"") is None
    assert parse_royalty_sale_script(bytes.fromhex("6a00")) is None      # OP_RETURN, not a covenant
    assert parse_royalty_sale_script(bytes.fromhex(COVHEX)[:-2]) is None  # truncated (drops OP_1 OP_ENDIF)
    assert parse_royalty_beacon(b"") is None
    assert parse_royalty_beacon(bytes.fromhex("6a04deadbeef5124" + REF_HEX)) is None  # wrong magic
    # A P2PKH (not OP_RETURN, not the covenant template) parses as neither.
    assert parse_royalty_sale_script(bytes.fromhex(P2PKH_HEX)) is None
    assert parse_royalty_beacon(bytes.fromhex(P2PKH_HEX)) is None
