# This file configures the Radiant Node for use with RXinDexer.
# It enables the required RPC settings and indexes for proper operation.

# RPC settings
server=1
rpcuser=dockeruser
rpcpassword=dockerpass
rpcport=7332
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

# Network settings - Add known stable peers to jumpstart sync
addnode=electrum.radiant4people.com
addnode=node1.radiant4people.com
addnode=node2.radiant4people.com
addnode=node3.radiant4people.com
addnode=radiant.mining4people.com
addnode=51.15.85.136
addnode=144.76.239.166
addnode=135.181.203.58
addnode=54.38.195.201:7333
addnode=170.205.37.208:7333
addnode=51.195.34.205:7333
addnode=38.114.121.180:7333
addnode=45.82.246.57:7333
addnode=173.234.30.37:7333
addnode=[2a01:4f9:3051:1417::2]:7333
addnode=57.129.64.36:7333

# Performance settings
dbcache=2048
maxconnections=40
listen=1
