# /Users/radiant/Desktop/RXinDexer/docker/grafana/provisioning/datasources/datasource.yml
# This file configures Grafana to use Prometheus as a data source.

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
